### ISSUE TITLE
Generate sitemap

### ISSUE THREAD

**Issue by jmikrut** [payloadcms/website#54]
Cross your fingers that it works with the /app folder

**Comment by jacobsfletch** [comment]
One way to do this is to open a custom endpoint in Payload that returns only an array of url strings per collection **_BUT_** since we're using GraphQL on the front-end, there is no need for this because we can build a query that does the exact same thing. Then using data, we can build the sitemap dynamically.

**Comment by jmikrut** [comment]
I used `next-sitemap` to accomplish this. It's done! 👍

**Comment by JarrodMFlesch** [comment]
I saw that, looks easy. Just a manual process but that's fine for us!

**Comment by jmikrut** [comment]
I added a postbuild command so at least it builds when the site deploys ☠️
